Create volume.dart in maths
TheAlgorithms/Dart pull request #158
Opened 2021-10-12 05:49 UTC by donfreddy

# Welcome to Dart community

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Dart files are placed inside an existing directory.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-10-20 08:44 UTC, akashgkrishnan approved these changes
LGTM @Parowicz

2022-09-28 04:02 UTC, akashgk requested changes
Also please add some references to the formulas on top of file for others to refer.

2022-09-28 04:02 UTC, akashgk commented on maths/volume.dart
> +double volPentagonalPrism(double pentagonalLength, double pentagonalBaseLength, double height) {
I think it would be better to rename the functions with complete words 
like `volumeOfCuboid` || `volumeOfCube`.

2022-09-28 04:02 UTC, akashgk commented on maths/volume.dart
> +/* Calculate the volume for a Cylinder */
lets not use single letter variables like `r` or `h`. can we use proper variable names like `radius` or `height`

2022-09-28 04:02 UTC, akashgk commented on maths/volume.dart
> +
unwanted spacing. run dart format on this file.

2026-06-05 20:54 UTC, closed without merging