Implement solution 20 for project euler
TheAlgorithms/Dart pull request #184
Opened 2022-10-02 11:56 UTC by G1Joshi

# Welcome to Dart community

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Dart files are placed inside an existing directory.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-03 13:02 UTC, akashgk commented on project_euler/problem_20/sol20.dart
> +  print(sum(number));
add test cases

2022-10-03 13:03 UTC, akashgk requested changes
LGTM! Please add some tests

2022-10-03 13:34 UTC, G1Joshi commented
> LGTM! Please add some tests

Thank you :)
I have added 3 test cases.

2022-10-03 14:34 UTC, akashgk commented on project_euler/problem_20/sol20.dart
> +      var actual = sum(1);
no need for variable declarations

2022-10-03 14:35 UTC, akashgk commented on project_euler/problem_20/sol20.dart
> +      expect(actual, matcher);
same

2022-10-03 14:35 UTC, akashgk commented on project_euler/problem_20/sol20.dart
> +      var actual = sum(10);
no need for variable declaration.

2022-10-03 14:36 UTC, akashgk requested changes
all is good. but we don't need to declare the variables for each case. just give the values directly to the function

Also, do a dart format on your file.

2022-10-03 14:43 UTC, G1Joshi commented
> all is good. but we don't need to declare the variables for each case. just give the values directly to the function
> 
> Also, do a dart format on your file.

Test cases are updated and the code is already formatted.

2022-10-07 12:22 UTC, akashgk commented
Thanks @G1Joshi

2022-10-07 12:22 UTC, merged