Create palindrome.dart
TheAlgorithms/Dart pull request #187
Opened 2022-10-07 13:15 UTC by satyamnoob

# Welcome to Dart community

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Dart files are placed inside an existing directory.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-07 13:17 UTC, satyamnoob commented
please add the label 'hacktoberfest-accepted' when accepting the pr request

2022-10-07 13:17 UTC, closed without merging

2022-10-07 13:35 UTC, akashgk requested changes
Please make the requested changes.

2022-10-07 13:50 UTC, satyamnoob commented on strings/palindrome.dart
> +    print('Its A Palindrome');
I am very new to this. What are tests? I will be updating everything as you requested

2022-10-07 13:52 UTC, akashgk commented on strings/palindrome.dart
> +    print('Its A Palindrome');
You can check out other files. to see how tests are implemented. 


You can also read up from the official docs:
https://pub.dev/packages/test

2022-10-08 05:41 UTC, satyamnoob commented
I have added the tests and other requirements. Do I need to do another pull request or you can see the changes? Sorry for asking dumb questions

2022-10-08 07:10 UTC, akashgk requested changes
Please address the change requests.

2022-10-08 07:10 UTC, akashgk commented on strings/palindrome.dart
> +
What's the use of this code section?

2022-10-08 07:10 UTC, akashgk commented on strings/palindrome.dart
> +  });
add negative cases

2022-10-08 07:10 UTC, akashgk commented on strings/palindrome.dart
> +}
All of the reversal logic are running on O(N) space. can we optimise to make it run on O(1) space.