Create Decimal_to_Octal
TheAlgorithms/Dart pull request #46
Opened 2020-09-16 12:19 UTC by mohammadreza490

2020-09-16 14:38 UTC, StepfenShawn requested changes
The filename should be `Decimal_to_Octal.dart`

2020-09-16 19:43 UTC, mohammadreza490 commented
> The filename should be `Decimal_to_Octal.dart`

Done

2020-09-17 04:39 UTC, StepfenShawn approved these changes

2020-09-17 04:39 UTC, merged

2020-09-17 04:39 UTC, StepfenShawn commented
Thanks!